### ISSUE TITLE
Support for updating URL script via the CLI

### ISSUE THREAD

**Issue by vmelikyan** [SpeedCurve-Metrics/speedcurve-cli#11]
**What kind of issue is this?**

- [x] Feature request / PR proposal
- [ ] Bug report
- [ ] Question

**Is this issue for the CLI, the Node.js API, or both?**
CLI

**What is the current behaviour?**
Currently there is no way for updating a URL script via the CLI

If you are reporting a bug, please write down the steps to reproduce the bug. If this is a feature request, please explain how the CLI or Node.js API does not meet your needs.

**What is the expected behaviour?**

Please describe how you think the CLI or Node.js API should behave.
I should be able to update URL script via the CLI

**Which version is affected by this issue? Did this work in previous versions?**
All

If you are reporting a bug, please also include your Node.js version, OS version, and any other information that might be helpful.

**Comment by josephwynn-sc** [comment]
Merged #12. Thank you!
