### ISSUE TITLE
CLI Exits with code 0 in the event of an error.

### ISSUE THREAD

**Issue by gapark** [SpeedCurve-Metrics/speedcurve-cli#16]
**What kind of issue is this?**

- [ ] Feature request / PR proposal
- [x] Bug report
- [ ] Question

**Is this issue for the CLI, the Node.js API, or both?**
The CLI

**What is the current behaviour?**
Currently we are utilising the `speedcurve` package in our CI pipelines to ensure we keep our core metrics under certain thresholds using the following command: `npx speedcurve deploy --site $SITE_NAME --check-budgets --key=$SPEEDCURVE_API_KEY`. This works beautifully when the tests can run, and exits with a non-0 code in the event that the tests fail. However, in the event of an error the exit code still appears to be 0. 

For example, if another pipeline is already running tests, or we have exceeded our monthly budget for tests, the CLI returns a JSON error message similar to the following:
```
{
  "status": "error",
  "message": "Unable to add a deploy. Checks per month budget exceeded for this Team. Please contact your Admin to increase budget for your Team or chat to SpeedCurve support about upgrading your account with more checks."
}
```

At present when an error such as this is thrown the job succeeds with an exit code of 0, allowing our pipeline to continue even if the tests have not been run.

**What is the expected behaviour?**
In the event that an error is thrown, we would expect a non-0 exit code to be returned to indicate that an error has occurred.

**Which version is affected by this issue? Did this work in previous versions?**
We are using `v2.1` of the `speedcurve` package with node `v14.15.4`.

**Comment by josephwynn-sc** [comment]
Thanks for reporting this! I'll do some tests to see how easy this would be to implement. The only complication I can think of is that when you run `speedcurve deploy` without a `--site` argument, it will run separate deploys for each site. It would be possible that some deploys succeed and some fail, so I'm not sure what the "correct" exit code would be. I guess a non-zero code would make sense to indicate that _something_ failed, even if other things were successful?

**Comment by gapark** [comment]
Thanks for looking into it, it is much appreciated. 

As for the issue you raised with multiple deploys, I personally feel that if even one fails then a non-zero exit code should still be returned. Just like you stated, something has indeed failed and so the CLI should indicate this, otherwise users continue to be left blind to any errors. 

An `--ignore-errors` flag could potentially be useful here to allow users to ignore any errors and return a 0 exit code even in the event of an error, whilst still returning a non-zero code if the tests themselves fail.
