### ISSUE TITLE
Bug: `npx speedcurve -h` does not print help when no api key is provided

### ISSUE THREAD

**Issue by jasikpark** [SpeedCurve-Metrics/speedcurve-cli#21]
**What kind of issue is this?**

- [ ] Feature request / PR proposal
- [X] Bug report
- [ ] Question

**Is this issue for the CLI, the Node.js API, or both?**
CLI
**What is the current behaviour?**

speedcurve cli complains that it has no api key and exits

**What is the expected behaviour?**

speedcurve should function for commands that don't require an api key w/o an api key provided.

**Which version is affected by this issue? Did this work in previous versions?**

If you are reporting a bug, please also include your Node.js version, OS version, and any other information that might be helpful.
speedcurve: 2.0.8
node: 16.16.0
macOS

**Comment by josephwynn-sc** [comment]
Thanks for reporting this and sorry for such a slow reply. I am about to release v2.0.9 which fixes this issue :)

**Comment by jasikpark** [comment]
great!
