### ISSUE TITLE
Deploying tests for a specific URL does not work in CLI or Node.js API

### ISSUE THREAD

**Issue by sergeychernyshev** [SpeedCurve-Metrics/speedcurve-cli#3]
**What kind of issue is this?**

- [ ] Feature request / PR proposal
- [x] Bug report
- [ ] Question

**Is this issue for the CLI, the Node.js API, or both?**
I only tested the CLI, but [Node.js API documentation](https://speedcurve-metrics.github.io/speedcurve-cli/modules/deploys.html#create) doesn't support urls parameter so I assume Node API doesn't work either.

**What is the current behaviour?**
`speedcurve deploy` command does not support a list of urls to be passed in even though [deploy API endpoint](https://api.speedcurve.com/#add-a-deploy) allows for that.

As a result, `speedcurve deploy --site 1234 --url 5678` runs tests for all URLs in the site with id of `1234` instead of only tests for url with id of `5678`.

**What is the expected behaviour?**
Node.js API should support `url` parameter (of type array) and CLI `speedcurve deploy` command should support `--url` parameters (optional, but allow multiple multiple) and run only the tests for provided URL IDs.

**Which version is affected by this issue? Did this work in previous versions?**
`speedcurve@1.0.6` ran with Node.js v8.11.4 on MacOS Mojave 10.14.3 (18D109)

**Comment by josephwynn-sc** [comment]
Thanks for this Sergey! Deploying for a single URL is a new(ish) feature and we haven't updated the CLI yet. I'll put it on my list of things to do this week.

**Comment by sergeychernyshev** [comment]
No problem, I tested that REST API works so wasn't too worried - will have it in my backpocket for people who want to test a subset of URLs.

**Comment by sergeychernyshev** [comment]
Did I mention that having this feature in UI would be awesome too? ;)

**Comment by josephwynn-sc** [comment]
Oops, I totally forgot to mark this as fixed! We added the `--url` flag to the deploy command.
