### ISSUE TITLE
Deploy url triggers whole site testing

### ISSUE THREAD

**Issue by MartinKristof** [SpeedCurve-Metrics/speedcurve-cli#30]
Hello,
the deploy testing for url has stopped working. It triggers whole site testing.
Command like: 

speedcurve deploy --url 110912

Yes, the passed urlId exists.

thank you

**Comment by josephwynn-sc** [comment]
Hi @MartinKristof, thanks for reporting this. I will investigate and get back to you ASAP.

**Comment by MartinKristof** [comment]
Hi!
Seems to be a bug in the v1 API. I tried using the command and the direct request. 
Already reported to Speedcurve.
Thank you!

**Comment by josephwynn-sc** [comment]
@MartinKristof we pushed a fix for this bug and single URL deploys should be working again. Thanks again for reporting this :)

**Comment by MartinKristof** [comment]
I am confirming. It is working now. Thank you!
